name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
        
      - name: Activate coverage
        run: pub global activate coverage

      - name: Test package
        run: dart test --coverage=coverage
        env:
          TOKEN: ${{ secrets.TOKEN }}
          TEST_DATABASE_ID: ${{ secrets.TEST_DATABASE_ID }}
          TEST_PAGE_ID: ${{ secrets.TEST_PAGE_ID }}
          TEST_BLOCK_ID: ${{ secrets.TEST_BLOCK_ID }}
          EXEC_ENV: 'github_actions'
          
      - name: Format coverage
        run: pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib

      - name: Upload coverge to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
